name: Print message workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: ./print-message@master
        with:
          message: "Hello, world!"
